language: node_js
node_js:
- 10.18.0
branchs:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_a2df9b418bbc_key -iv $encrypted_a2df9b418bbc_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.104.15.110\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- git pull
- rm -f yarn-lock.json && yarn
script:
- yarn build
after_success:
- rm -rf root@39.104.15.110:/home/www/react_pc/*
- scp -r ./build/* root@39.104.15.110:/home/www/react_pc
