language: node_js
node_js:
- 10.18.0
branchs:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
install:
- git pull
- rm -f yarn-lock.json && yarn
script:
- yarn build
after_success: 
- chmod 600 ~/.ssh/id_rsa
- rm -rf /var/www/react_pc/*
- scp -o stricthostkeychecking=no -r ./build/* /var/www/react_pc
before_install:
- openssl aes-256-cbc -K $encrypted_dfd5fdc6b788_key -iv $encrypted_dfd5fdc6b788_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
