language: node_js
node_js:
- 8.9.1
branchs:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
install:
- git pull
- rm -f package-lock.json && cnpm install
script:
- cnpm run build
after_success: 
- chmod 600 ~/.ssh/id_rsa
- scp -o stricthostkeychecking=no -r ./build/* travis@118.24.157.36:/var/www/react_pc
before_install:
- openssl aes-256-cbc -K $encrypted_dfd5fdc6b788_key -iv $encrypted_dfd5fdc6b788_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
