export const LOGIN = 'login/LOGIN'
export const LOGIN_SUCCESS = 'login/LOGIN_SUCCESS'
export const LOGOUT = 'login/LOGINOUT'
export const REGISTER = 'login/REGISTER'
export const REGISTER_SUCCESS = 'register/REGISTER_SUCCESS'